; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = native

[env:uno]
platform = atmelavr
board = uno
framework = arduino
test_framework = unity
test_filter = test_hardware

[env:native]
platform = native
test_framework = unity
build_src_filter = +<../lib/algorithms/> -<../lib/hardware/>
test_filter = test_pid, test_ema, test_protocol
lib_deps = throwtheswitch/Unity@^2.5.2
build_flags = -I test