[platformio]
default_envs = native

[env:uno]
platform = atmelavr
board = uno
framework = arduino
test_framework = unity
test_filter = test_hardware
test_speed = 115200
test_port = COM11
monitor_speed = 115200

[env:native]
platform = native
test_framework = unity
build_src_filter = +<../lib/algorithms/> -<../lib/hardware/>
test_filter = test_pid, test_ema, test_protocol